### ISSUE TITLE
framework does not compile for nullptr assert

### ISSUE THREAD

**Issue by unjello** [DronMDF/upp11#1]
when comparing UP_ASSERT_EQUAL or UP_ASSERT_NE with nullptr, it gives a following error:

> > upp11.h:368:6: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::ostringstream {aka std::basic_ostringstream<char>}’ and ‘std::nullptr_t’)
> >    os << tt;

**Comment by DronMDF** [comment]
Thank's for feedback...
ASERT_EQUAL not tested with pointers.

Comparsion for pointers are passed?
